/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.bill;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import javax.swing.JComponent;

/**
 *
 * @author dante
 */
public class JPanelCertificado extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {

    /**
     * Creates new form JPanelReglasFacturas
     */
    public JPanelCertificado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        m_jCheckBoxEnabled = new javax.swing.JCheckBox();
        m_jCheckBoxBasedOnRules = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPac = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        m_jLblCertificate = new javax.swing.JLabel();
        m_jBtnCertificado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        m_jLblKey = new javax.swing.JLabel();
        m_jBtnLlave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        m_jPasswordFiel = new javax.swing.JPasswordField();
        m_jBtnValidar = new javax.swing.JButton();

        m_jCheckBoxEnabled.setText("Habilitado");
        jPanel5.add(m_jCheckBoxEnabled);

        m_jCheckBoxBasedOnRules.setText("Facturar basado en Reglas Automáticas");
        jPanel5.add(m_jCheckBoxBasedOnRules);

        add(jPanel5);

        jLabel1.setText("Proveedor Autorizado de Certificados (PAC): ");
        jPanel7.add(jLabel1);

        jComboBoxPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ProFact", "Click Factura" }));
        jComboBoxPac.setName(""); // NOI18N
        jPanel7.add(jComboBoxPac);

        add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(3, 3));

        jLabel3.setText("Certificado (.crt)");
        jPanel8.add(jLabel3);

        m_jLblCertificate.setBackground(java.awt.Color.white);
        m_jLblCertificate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        m_jLblCertificate.setMaximumSize(new java.awt.Dimension(10, 4));
        m_jLblCertificate.setMinimumSize(new java.awt.Dimension(10, 4));
        m_jLblCertificate.setOpaque(true);
        m_jLblCertificate.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel8.add(m_jLblCertificate);

        m_jBtnCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/search22.png"))); // NOI18N
        m_jBtnCertificado.setToolTipText("Buscar .crt");
        m_jBtnCertificado.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnCertificado.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanel8.add(m_jBtnCertificado);

        jLabel4.setText("Llave Privada (.key)");
        jPanel8.add(jLabel4);

        m_jLblKey.setBackground(java.awt.Color.white);
        m_jLblKey.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        m_jLblKey.setMaximumSize(new java.awt.Dimension(10, 4));
        m_jLblKey.setMinimumSize(new java.awt.Dimension(10, 4));
        m_jLblKey.setOpaque(true);
        m_jLblKey.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel8.add(m_jLblKey);

        m_jBtnLlave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/search22.png"))); // NOI18N
        m_jBtnLlave.setToolTipText("Buscar .key");
        m_jBtnLlave.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnLlave.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanel8.add(m_jBtnLlave);

        jLabel5.setText("Password");
        jPanel8.add(jLabel5);

        m_jPasswordFiel.setText("jPasswordField1");
        jPanel8.add(m_jPasswordFiel);

        m_jBtnValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/button_ok.png"))); // NOI18N
        m_jBtnValidar.setToolTipText("Validar");
        m_jBtnValidar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnValidar.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanel8.add(m_jBtnValidar);

        add(jPanel8);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton m_jBtnCertificado;
    private javax.swing.JButton m_jBtnLlave;
    private javax.swing.JButton m_jBtnValidar;
    private javax.swing.JCheckBox m_jCheckBoxBasedOnRules;
    private javax.swing.JCheckBox m_jCheckBoxEnabled;
    private javax.swing.JLabel m_jLblCertificate;
    private javax.swing.JLabel m_jLblKey;
    private javax.swing.JPasswordField m_jPasswordFiel;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return "";
    }

    @Override
    public void activate() throws BasicException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean deactivate() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return true;
        
    }

    @Override
    public JComponent getComponent() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return this;
    }

    @Override
    public void init(AppView app) throws BeanFactoryException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getBean() {
        return this;
    }
}
