/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.bill;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.pos.customers.DataLogicCustomers;
import com.openbravo.pos.customers.JCustomerFinder;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import javax.swing.JComponent;

/**
 *
 * @author dante
 */
public class JPanelFacturas extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {
    
    protected AppView m_App;
    protected DataLogicCustomers dlCustomers;

    /**
     * Creates new form JPanelBills
     */
    public JPanelFacturas() {
        initComponents();
    }
    
    public void init(AppView app) throws BeanFactoryException {
        m_App = app;
        dlCustomers = (DataLogicCustomers) m_App.getBean("com.openbravo.pos.customers.DataLogicCustomers");
    }

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {
        JCustomerFinder finder = JCustomerFinder.getCustomerFinder(this, dlCustomers);
        // finder.search(m_oTicket.getCustomer());
        finder.setVisible(true);
        /*
        try {
            m_oTicket.setCustomer(finder.getSelectedCustomer() == null
                    ? null
                    : dlSales.loadCustomerExt(finder.getSelectedCustomer().getId()));
        } catch (BasicException e) {
            MessageInf msg = new MessageInf(MessageInf.SGN_WARNING, AppLocal.getIntString("message.cannotfindcustomer"), e);
            msg.show(this);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanelFiltro = new javax.swing.JPanel();
        jPanelDatos = new javax.swing.JPanel();
        jPanelFechas = new javax.swing.JPanel();
        jLblDesde = new javax.swing.JLabel();
        m_jLblDesdeValue = new javax.swing.JLabel();
        m_jBtnDesde = new javax.swing.JButton();
        jLblHasta = new javax.swing.JLabel();
        m_jLblHastaValue = new javax.swing.JLabel();
        m_jBtnHasta = new javax.swing.JButton();
        jPanelEntidades = new javax.swing.JPanel();
        jPanelCliente = new javax.swing.JPanel();
        jLblCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_jBtnCliente = new javax.swing.JButton();
        jPanelTicket = new javax.swing.JPanel();
        jLblTicket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m_jBtnTicket = new javax.swing.JButton();
        jPanelProducto = new javax.swing.JPanel();
        jLblProducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m_jBtnProducto = new javax.swing.JButton();
        jPanelBotones = new javax.swing.JPanel();
        m_jBtnBuscar = new javax.swing.JButton();
        m_jBtnReenviar = new javax.swing.JButton();
        m_jBtnCancelar = new javax.swing.JButton();
        jPanelDetail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_jTblFacturas = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanelFiltro.setLayout(new javax.swing.BoxLayout(jPanelFiltro, javax.swing.BoxLayout.Y_AXIS));

        jPanelDatos.setLayout(new javax.swing.BoxLayout(jPanelDatos, javax.swing.BoxLayout.Y_AXIS));

        jPanelFechas.setMinimumSize(new java.awt.Dimension(214, 38));
        jPanelFechas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblDesde.setText("Desde:");
        jPanelFechas.add(jLblDesde);

        m_jLblDesdeValue.setBackground(java.awt.Color.white);
        m_jLblDesdeValue.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        m_jLblDesdeValue.setMaximumSize(new java.awt.Dimension(10, 4));
        m_jLblDesdeValue.setMinimumSize(new java.awt.Dimension(10, 4));
        m_jLblDesdeValue.setOpaque(true);
        m_jLblDesdeValue.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanelFechas.add(m_jLblDesdeValue);
        m_jLblDesdeValue.getAccessibleContext().setAccessibleName("m_jLblDesdeValue");

        m_jBtnDesde.setIcon(new javax.swing.ImageIcon("/Users/dante/NetBeansProjects/openbravopos_2.30.2_src/src-beans/com/openbravo/images/date.png")); // NOI18N
        m_jBtnDesde.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnDesde.setPreferredSize(new java.awt.Dimension(56, 44));
        m_jBtnDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jBtnDesdeActionPerformed(evt);
            }
        });
        jPanelFechas.add(m_jBtnDesde);

        jLblHasta.setText("Hasta:");
        jPanelFechas.add(jLblHasta);

        m_jLblHastaValue.setBackground(new java.awt.Color(255, 255, 255));
        m_jLblHastaValue.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        m_jLblHastaValue.setMaximumSize(new java.awt.Dimension(10, 4));
        m_jLblHastaValue.setMinimumSize(new java.awt.Dimension(10, 4));
        m_jLblHastaValue.setOpaque(true);
        m_jLblHastaValue.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanelFechas.add(m_jLblHastaValue);

        m_jBtnHasta.setIcon(new javax.swing.ImageIcon("/Users/dante/NetBeansProjects/openbravopos_2.30.2_src/src-beans/com/openbravo/images/date.png")); // NOI18N
        m_jBtnHasta.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnHasta.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanelFechas.add(m_jBtnHasta);

        jPanelDatos.add(jPanelFechas);

        jPanelEntidades.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLblCliente.setText("Cliente:");
        jPanelCliente.add(jLblCliente);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        jLabel3.setMaximumSize(new java.awt.Dimension(10, 4));
        jLabel3.setMinimumSize(new java.awt.Dimension(10, 4));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(160, 25));
        jLabel3.setSize(new java.awt.Dimension(160, 25));
        jPanelCliente.add(jLabel3);

        m_jBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/kuser.png"))); // NOI18N
        m_jBtnCliente.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnCliente.setPreferredSize(new java.awt.Dimension(56, 44));
        m_jBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jBtnClienteActionPerformed(evt);
            }
        });
        jPanelCliente.add(m_jBtnCliente);

        jPanelEntidades.add(jPanelCliente);

        jLblTicket.setText("Ticket:");
        jPanelTicket.add(jLblTicket);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        jLabel4.setMaximumSize(new java.awt.Dimension(10, 4));
        jLabel4.setMinimumSize(new java.awt.Dimension(10, 4));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(160, 25));
        jLabel4.setSize(new java.awt.Dimension(160, 25));
        jPanelTicket.add(jLabel4);

        m_jBtnTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/mime.png"))); // NOI18N
        m_jBtnTicket.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnTicket.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanelTicket.add(m_jBtnTicket);

        jPanelEntidades.add(jPanelTicket);

        jLblProducto.setText("Producto:");
        jPanelProducto.add(jLblProducto);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        jLabel5.setMaximumSize(new java.awt.Dimension(10, 4));
        jLabel5.setMinimumSize(new java.awt.Dimension(10, 4));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(160, 25));
        jLabel5.setSize(new java.awt.Dimension(160, 25));
        jPanelProducto.add(jLabel5);

        m_jBtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ark216.png"))); // NOI18N
        m_jBtnProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnProducto.setPreferredSize(new java.awt.Dimension(56, 44));
        jPanelProducto.add(m_jBtnProducto);

        jPanelEntidades.add(jPanelProducto);

        jPanelDatos.add(jPanelEntidades);

        jPanelFiltro.add(jPanelDatos);

        m_jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/launch.png"))); // NOI18N
        m_jBtnBuscar.setText("Buscar");
        m_jBtnBuscar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnBuscar.setPreferredSize(new java.awt.Dimension(95, 44));
        jPanelBotones.add(m_jBtnBuscar);

        m_jBtnReenviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ark216.png"))); // NOI18N
        m_jBtnReenviar.setText("Reenviar");
        m_jBtnReenviar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnReenviar.setPreferredSize(new java.awt.Dimension(95, 44));
        m_jBtnReenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jBtnReenviarActionPerformed(evt);
            }
        });
        jPanelBotones.add(m_jBtnReenviar);

        m_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/editdelete.png"))); // NOI18N
        m_jBtnCancelar.setText("Cancelar");
        m_jBtnCancelar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m_jBtnCancelar.setPreferredSize(new java.awt.Dimension(95, 44));
        m_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jBtnCancelarActionPerformed(evt);
            }
        });
        jPanelBotones.add(m_jBtnCancelar);

        jPanelFiltro.add(jPanelBotones);

        add(jPanelFiltro);

        jPanelDetail.setLayout(new java.awt.BorderLayout());

        m_jTblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha Compra", "Factura", "Fecha Factura", "Estatus", "Ticket", "Cliente", "email", "Importe", "# Productos", "Proveedor", "Reenviar", "Cancelar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        m_jTblFacturas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(m_jTblFacturas);
        m_jTblFacturas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanelDetail.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanelDetail);
    }// </editor-fold>//GEN-END:initComponents

    private void m_jBtnReenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jBtnReenviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jBtnReenviarActionPerformed

    private void m_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jBtnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jBtnCancelarActionPerformed

    private void m_jBtnDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jBtnDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jBtnDesdeActionPerformed

    private void m_jBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jBtnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jBtnClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JLabel jLblDesde;
    private javax.swing.JLabel jLblHasta;
    private javax.swing.JLabel jLblProducto;
    private javax.swing.JLabel jLblTicket;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPanel jPanelEntidades;
    private javax.swing.JPanel jPanelFechas;
    private javax.swing.JPanel jPanelFiltro;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m_jBtnBuscar;
    private javax.swing.JButton m_jBtnCancelar;
    private javax.swing.JButton m_jBtnCliente;
    private javax.swing.JButton m_jBtnDesde;
    private javax.swing.JButton m_jBtnHasta;
    private javax.swing.JButton m_jBtnProducto;
    private javax.swing.JButton m_jBtnReenviar;
    private javax.swing.JButton m_jBtnTicket;
    private javax.swing.JLabel m_jLblDesdeValue;
    private javax.swing.JLabel m_jLblHastaValue;
    private javax.swing.JTable m_jTblFacturas;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return "";
    }

    @Override
    public void activate() throws BasicException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean deactivate() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return true;
    }

    @Override
    public JComponent getComponent() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return this;
    }

    @Override
    public Object getBean() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return this;
    }
}
